# Generated by Django 3.2.16 on 2022-11-30 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200, verbose_name='項目')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='題名')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_day', models.DateTimeField(auto_now_add=True, verbose_name='順番用')),
                ('day', models.DateField(auto_now_add=True, verbose_name='登録日時')),
                ('reply_title', models.CharField(max_length=200, verbose_name='返信内容')),
                ('reply', models.DateField(default=False, verbose_name='返信用封筒はいつまでですか')),
                ('image', models.ImageField(upload_to='images/', verbose_name='写真（画像）')),
                ('Top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.top')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_day', models.DateTimeField(auto_now_add=True, verbose_name='順番用')),
                ('day', models.DateField(auto_now_add=True, verbose_name='登録日時')),
                ('notice', models.CharField(max_length=200, verbose_name='お知らせ')),
                ('image', models.ImageField(upload_to='images/', verbose_name='写真（画像）')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listof')),
            ],
        ),
        migrations.AddField(
            model_name='listof',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.top'),
        ),
    ]
